# EXCEPTIONS - TRY
try:
    n1 = int(input("Mete un numero: "))
except:
    print("Error!")